jdk: openjdk11

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database pouch;' -U postgres

script:
  - ./gradlew check build deployHeroku

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
