# Schematic to build Docker containers for project database
version: '3.1'

services:

  db:
    image: postgres:latest
    container_name: pouch_db
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pouch_database

  adminer:
    image: adminer
    container_name: pouch_adminer
    restart: always
    ports:
    - 8181:8080
